const products = [
  {
    id: 0,
    name: "S117",
    price: 85,
    instock: 100,
    description: "Tableau décoratif 3 pièces.",
    imgSrc: "./img/t1.png",
  },
  {
    id: 1,
    name: "C343",
    price: 30,
    instock: 43,
    description: "Tableau décoratif 4 pièces.",
    imgSrc: "./img/t2.png",
  },
  {
    id: 2,
    name: "C1012",
    price: 40,
    instock: 10,
    description: "Tableau décoratif 5 pièces.",
    imgSrc: "./img/t3.png",
  },
  {
    id: 3,
    name: "S243",
    price: 52,
    instock: 5,
    description: "Tableau décoratif 6 pièces.",
    imgSrc: "./img/t4.png",
  },
  {
    id: 4,
    name: "S219",
    price: 25,
    instock: 4,
    description: "Tableau décoratif 3 pièces.",
    imgSrc: "./img/t5.png",
  },
  {
    id: 5,
    name: "S211",
    price: 30,
    instock: 40,
    description: "Tableau décoratif 5 pièces.",
    imgSrc: "./img/t6.png",
  },
];
